"""Core types for Agent-First Development.

This module contains the foundational types used across all AFD applications:
- CommandResult: Standard response type for all commands
- CommandError: Structured error with recovery guidance
- Metadata types: Source, PlanStep, Alternative, Warning
- Handoff types: HandoffResult, HandoffCredentials, HandoffMetadata
- Telemetry types: TelemetryEvent, TelemetrySink, ConsoleTelemetrySink
"""

from afd.core.result import (
    CommandResult,
    ResultMetadata,
    success,
    failure,
    error,
    is_success,
    is_failure,
)
from afd.core.errors import (
    CommandError,
    ErrorCodes,
    create_error,
    validation_error,
    not_found_error,
    rate_limit_error,
    timeout_error,
    internal_error,
    wrap_error,
    is_command_error,
)
from afd.core.metadata import (
    Source,
    PlanStep,
    PlanStepStatus,
    Alternative,
    Warning,
    WarningSeverity,
    create_source,
    create_step,
    update_step_status,
    create_warning,
)
from afd.core.commands import (
    CommandParameter,
    CommandDefinition,
    CommandHandler,
    CommandContext,
    CommandRegistry,
    ExposeOptions,
    DEFAULT_EXPOSE,
    create_command_registry,
)
from afd.core.mcp_types import (
    MCP_PROTOCOL_VERSION,
    JSONRPC_VERSION,
    TextContent,
    ImageContent,
    EmbeddedResource,
    Content,
    ToolInputSchema,
    ToolDefinition,
    ToolCallParams,
    ToolResult,
    JsonRpcError,
    McpRequest,
    McpResponse,
    McpErrorResponse,
    ClientInfo,
    ServerInfo,
    InitializeParams,
    InitializeResult,
    text_content,
    image_content,
    embedded_resource,
    tool_call_params,
    tool_result,
    tool_definition,
    mcp_request,
    mcp_response,
    mcp_error_response,
    initialize_params,
    initialize_result,
)
from afd.core.telemetry import (
    TelemetryEvent,
    TelemetrySink,
    ConsoleTelemetrySink,
    create_telemetry_event,
    is_telemetry_event,
)
from afd.core.handoff import (
    HandoffProtocol,
    HandoffCredentials,
    HandoffMetadata,
    HandoffResult,
    ReconnectPolicy,
    is_handoff,
    is_handoff_protocol,
    is_handoff_command,
    get_handoff_protocol,
    create_handoff,
)
from afd.core.batch import (
    BatchCommand,
    BatchOptions,
    BatchRequest,
    BatchCommandResult,
    BatchSummary,
    BatchTiming,
    BatchWarning,
    BatchResult,
    create_batch_request,
    calculate_batch_confidence,
    create_batch_result,
    create_failed_batch_result,
    is_batch_request,
    is_batch_result,
    is_batch_command,
)
from afd.core.streaming import (
    ProgressChunk,
    DataChunk,
    CompleteChunk,
    ErrorChunk,
    StreamChunk,
    StreamOptions,
    StreamCallbacks,
    StreamableCommand,
    create_progress_chunk,
    create_data_chunk,
    create_complete_chunk,
    create_error_chunk,
    is_progress_chunk,
    is_data_chunk,
    is_complete_chunk,
    is_error_chunk,
    is_stream_chunk,
    is_streamable_command,
    consume_stream,
    collect_stream_data,
)

__all__ = [
    # Result types
    "CommandResult",
    "ResultMetadata",
    "success",
    "failure",
    "error",
    "is_success",
    "is_failure",
    # Error types
    "CommandError",
    "ErrorCodes",
    "create_error",
    "validation_error",
    "not_found_error",
    "rate_limit_error",
    "timeout_error",
    "internal_error",
    "wrap_error",
    "is_command_error",
    # Metadata types
    "Source",
    "PlanStep",
    "PlanStepStatus",
    "Alternative",
    "Warning",
    "WarningSeverity",
    "create_source",
    "create_step",
    "update_step_status",
    "create_warning",
    # Command types
    "CommandParameter",
    "CommandDefinition",
    "CommandHandler",
    "CommandContext",
    "CommandRegistry",
    "ExposeOptions",
    "DEFAULT_EXPOSE",
    "create_command_registry",
    # MCP protocol types
    "MCP_PROTOCOL_VERSION",
    "JSONRPC_VERSION",
    "TextContent",
    "ImageContent",
    "EmbeddedResource",
    "Content",
    "ToolInputSchema",
    "ToolDefinition",
    "ToolCallParams",
    "ToolResult",
    "JsonRpcError",
    "McpRequest",
    "McpResponse",
    "McpErrorResponse",
    "ClientInfo",
    "ServerInfo",
    "InitializeParams",
    "InitializeResult",
    "text_content",
    "image_content",
    "embedded_resource",
    "tool_call_params",
    "tool_result",
    "tool_definition",
    "mcp_request",
    "mcp_response",
    "mcp_error_response",
    "initialize_params",
    "initialize_result",
    # Telemetry types
    "TelemetryEvent",
    "TelemetrySink",
    "ConsoleTelemetrySink",
    "create_telemetry_event",
    "is_telemetry_event",
    # Handoff types
    "HandoffProtocol",
    "HandoffCredentials",
    "HandoffMetadata",
    "HandoffResult",
    "ReconnectPolicy",
    "is_handoff",
    "is_handoff_protocol",
    "is_handoff_command",
    "get_handoff_protocol",
    "create_handoff",
    # Batch types
    "BatchCommand",
    "BatchOptions",
    "BatchRequest",
    "BatchCommandResult",
    "BatchSummary",
    "BatchTiming",
    "BatchWarning",
    "BatchResult",
    "create_batch_request",
    "calculate_batch_confidence",
    "create_batch_result",
    "create_failed_batch_result",
    "is_batch_request",
    "is_batch_result",
    "is_batch_command",
    # Streaming types
    "ProgressChunk",
    "DataChunk",
    "CompleteChunk",
    "ErrorChunk",
    "StreamChunk",
    "StreamOptions",
    "StreamCallbacks",
    "StreamableCommand",
    "create_progress_chunk",
    "create_data_chunk",
    "create_complete_chunk",
    "create_error_chunk",
    "is_progress_chunk",
    "is_data_chunk",
    "is_complete_chunk",
    "is_error_chunk",
    "is_stream_chunk",
    "is_streamable_command",
    "consume_stream",
    "collect_stream_data",
]
